Rewrite to json from bson
scifio/scifio-labeling pull request #3
Opened 2022-04-06 09:42 UTC by tomburke-rse

Most of the API has been moved to JSON. 
The function-based mapping still needs to be solved.

Minimal changelog:

- Change to API, mostly removal of most class arguments.
- Removal of bson/mongo dependancy
- add gson dependancy
- Update tests in accordance

If this all looks fine with you @gselzer, feel free to merge, build and release.

2022-04-06 14:55 UTC, gselzer requested changes
Thanks for this @tomburke-rse! It looks a lot better!

I had some comments, mostly about making the code DRYer.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +    private Gson gson;
Can you not just write `private final Gson gson = new Gson();`? And then remove `initialize()`?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
>      private Context context;
IntelliJ is telling me that you never use this. Can we delete it?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
>      private DatasetIOService datasetIOService;
IntelliJ is telling me that you never use this. Can we delete it?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        int version = labelingData.getVersion();
This is unused in the method.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        int numSources = labelingData.getNumSources();
This is also unused.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        return ImgLabeling.fromImageAndLabelSets(img,  labelSets);
This `return` should go within the try block. Otherwise, if you catch that `IOException`, you'll probably get an NPE out of `ImgLabeling.fromImageAndLabelSets(img, labelSets)`, no?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        return ImgLabeling.fromImageAndLabelSets(img,  labelSets);
This is now the exact same code as `DefaultLabelingIOService.load(String file)`, right? The only difference is that this one takes `Class<T> clazz`, which it never uses? It would be DRYer if we just had one method (probably the one that just takes the `String`) just call this one.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        container.setImgLabeling(ImgLabeling.fromImageAndLabelSets(img,  labelSets));
Could this just be replaced by
```java
Container container = new Container<>();
container.setImgLabeling(load(file));
```

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        container.setImgLabeling(ImgLabeling.fromImageAndLabelSets(img,  labelSets));
Ah, no, it can't be, cause of the usage of `labelingData` below. 😦 

Can we at least write a helper to reduce the code duplication?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +    public <S, T, I extends IntegerType<I>> Container<S, T, I> loadWithMetadata(String file, LongFunction<T> idToLabel, Class<S> metadataClazz) throws IOException {
Similarly, this method never uses `idToLabel`. It should just call `loadWithMetadata(file, metadataClazz)`.

Do we have good use cases for these methods in `LabelingIOService`?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        LabelingData labelingData = gson.fromJson(reader, LabelingData.class);
Can we generify `LabelingData` (i.e. write `LabelingData<T, Object>`?) That would be the correct generics here.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        labelingData.setMetadata(metadata);
The only difference between the above method and this one is this line, yeah? Is there a way that we can be DRYer?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        labelingData.setMetadata(metadata);
I rather dislike this, but at the very least you could allow `metadata` to be null, and then write:
```java
if (metadata != null) labelingData.setMetadata(metadata);
```

That would reduce `save(ImgLabeling<T, I> imgLabeling, String file)`'s body to:
```
save(imgLabeling, file, null)
```

Of course a null check in the methods feels like a code smell...

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        if(labelingMapping.getLabels().stream().findFirst().get() instanceof Integer){
Do you need to worry about this `Optional` being empty? Doesn't `Optional` have some getOrDefault method?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        if(labelingMapping.getLabels().stream().findFirst().get() instanceof Integer){
Ah, it's `Optional.orElseGet(Supplier<? extends T> other)`

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +            Map<String, Set<Integer>> labels = new HashMap<>();
There seems like a lot of code repetition in this `else` block. Can we just always populate the `labelSets` like above, and then populate `labelMapping` if the labels are not `Integer`s?

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +                for(int j : (Set<Integer>) labelingData.getLabelSets().get(Integer.toString(i))){
The cast to set is apparently unnecessary

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +            labelSets = new ArrayList<>();
This initialization can be done on line 232 and this line and 234 can be deleted.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +    private <T, S> LabelingData<T,S> createBasicLabelingData(String file, LabelingMapping<T> labelingMapping) {
The `S` type parameter is vacuous and should be replaced with `Object`.

2022-04-06 14:55 UTC, gselzer commented on src/main/java/net/imglib2/labeling/LabelingIOService.java
>      <T, I extends IntegerType<I>> ImgLabeling<T,I> load(String file) throws IOException;
This doesn't pertain to this PR per se, but it sucks that there are vacuous type parameters in this API. There is nothing to stop me from writing

```
        ImgLabeling<Object, UnsignedByteType> imgLabeling = labelingIOService.load("src/test/resources/labeling/test");
```

Which could throw some gross `ClassCastException`s.

2022-04-06 14:55 UTC, gselzer commented on src/test/java/net/imglib2/labeling/LabelingIOTest.java
> +//        Container<Example, Example, IntType> container = labelingIOService.loadWithMetadata("src/test/resources/labeling/labelSaveTestComplex.bson", Example.class,  Example.class, new ExampleCodec(
All these codec tests should just be deleted, yeah?

2022-04-06 14:55 UTC, gselzer commented on src/test/java/net/imglib2/labeling/LabelingIOTest.java
> +        Img<UnsignedByteType> indexImg = ArrayImgs.unsignedBytes(new byte[]{1, 0, 2}, 1);
What is the point of this change?

2022-04-06 14:55 UTC, gselzer commented on src/test/java/net/imglib2/labeling/tutorials/E01_LoadLabeling.java
> +//        Container<Example, Example, IntType> container = labelingIOService.loadWithMetadata("src/test/resources/labeling/labelSaveTestComplexFunction.bson", map::get, Example.class, new ExampleCode
Can we just delete these tutorials? Better than commented out, imo.

2022-04-06 14:57 UTC, gselzer commented on src/main/java/net/imglib2/labeling/LabelingIOService.java
>      <T, I extends IntegerType<I>> ImgLabeling<T,I> load(String file) throws IOException;
See https://github.com/scifio/Labeling/issues/4

2022-04-06 15:15 UTC, tomburke-rse commented on src/test/java/net/imglib2/labeling/tutorials/E01_LoadLabeling.java
> +//        Container<Example, Example, IntType> container = labelingIOService.loadWithMetadata("src/test/resources/labeling/labelSaveTestComplexFunction.bson", map::get, Example.class, new ExampleCode
I just have to fix them really, but didn't consider them critical for the PR

2022-04-06 15:15 UTC, tomburke-rse commented on src/test/java/net/imglib2/labeling/LabelingIOTest.java
> +//        Container<Example, Example, IntType> container = labelingIOService.loadWithMetadata("src/test/resources/labeling/labelSaveTestComplex.bson", Example.class,  Example.class, new ExampleCodec(
Yes, there are no more codecs in the code.

2022-04-06 15:16 UTC, tomburke-rse commented on src/main/java/net/imglib2/labeling/LabelingIOService.java
>      <T, I extends IntegerType<I>> ImgLabeling<T,I> load(String file) throws IOException;
Unfortunately yes and that's what's also giving me major headaches on how to solve it if I want to stay fully compatible with the typed API of ImgLib2

2022-04-06 15:18 UTC, tomburke-rse commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +    private Gson gson;
I can move it up, but I can't get rid of the initialize(), since that comes from the Service interface

2022-04-06 15:19 UTC, tomburke-rse commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
>      private DatasetIOService datasetIOService;
Is used in line89. IntellJ says it's never assigned, which happens through the plugin api.

2022-04-06 16:05 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +    private Gson gson;
Why not? It's just an overriden method, yeah? If it's empty then you shouldn't need to declare it. Is there something I'm missing?

2022-04-06 16:09 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
>      private DatasetIOService datasetIOService;
Oop, you're right! My bad!

2022-04-06 16:10 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
>      private Context context;
I also misread this. Ignore me!

2022-04-06 16:17 UTC, gselzer commented on src/main/java/net/imglib2/labeling/LabelingIOService.java
>      <T, I extends IntegerType<I>> ImgLabeling<T,I> load(String file) throws IOException;
Well, I don't think you can solve it. I'd probably just deprecate those methods and write a new method with the correct generics. Unfortunately you'd have to name it something different. 😦

I suppose we should discuss in that issue.

2022-04-06 16:18 UTC, gselzer commented on src/test/java/net/imglib2/labeling/tutorials/E01_LoadLabeling.java
> +//        Container<Example, Example, IntType> container = labelingIOService.loadWithMetadata("src/test/resources/labeling/labelSaveTestComplexFunction.bson", map::get, Example.class, new ExampleCode
:+1:

2022-04-18 19:46 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +            labelSets = new ArrayList<>();
Fixed on 400bae1

2022-04-18 20:04 UTC, gselzer approved these changes

2022-04-18 20:04 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +import sun.reflect.generics.reflectiveObjects.NotImplementedException;
Can we use `UnsupportedOperationException` here?

It is not good practice to use internal API, as it could be removed from the JDK at any time. See [here](https://stackoverflow.com/a/16374284).

2022-04-18 20:32 UTC, tomburke-rse commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +import sun.reflect.generics.reflectiveObjects.NotImplementedException;
I plan to remove that next week and implement the methods. Just wanted to get a minimal runnin prject so that you can continue on pyimagej

2022-04-20 16:16 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +import sun.reflect.generics.reflectiveObjects.NotImplementedException;
Sounds good, I fixed it anyways.

2022-04-20 16:22 UTC, gselzer commented on src/test/java/net/imglib2/labeling/LabelingIOTest.java
> +        Img<UnsignedByteType> indexImg = ArrayImgs.unsignedBytes(new byte[]{1, 0, 2}, 1);
Ah, I see, now it corresponds to a label of 2!

2022-04-20 18:15 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +        if(labelingMapping.getLabels().stream().findFirst().get() instanceof Integer){
Fixed with ebf4c5a

2022-04-20 18:18 UTC, gselzer commented on src/main/java/net/imglib2/labeling/DefaultLabelingIOService.java
> +            Map<String, Set<Integer>> labels = new HashMap<>();
Just gonna ignore this for now, in the interest of merging.

2022-04-20 18:30 UTC, gselzer commented
@tomburke-rse at this point it builds with passing tests.

Let's merge (and release) it!

2022-04-20 18:36 UTC, ctrueden commented
I tested all commits and rewrote the message of the WIP commit to reflect that it is not a WIP (it successfully compiles with passing tests). Should be good to merge now, so I'm doing it.

2022-04-20 18:36 UTC, merged